In [1]:
# Librerías principales

import pandas as pd
import numpy as np

# Visualización
import plotly.express as px
import plotly.graph_objects as go

# SQL
import duckdb

# Configuración para mostrar más columnas
pd.set_option('display.max_columns', None)

In [3]:
# Cargar dataset

df = pd.read_csv("/content/sample_data/talabat_enhanced_orders.csv")

# Mostrar primeras filas
df.head()

,Order_ID,User_ID,Restaurant_ID,Driver_ID,Item_Name,Quantity,Total_Price,Order_Time,Delivery_Time,Delivery_Duration_Minutes,City,Payment_Method,Order_Status,Driver_Vehicle,Restaurant_Lat,Restaurant_Lon,Customer_Lat,Customer_Lon,Driver_Lat,Driver_Lon,Delivery_Distance_km,Traffic_Level,Driver_Availability
0,1,U3522,358,485,Fried Chicken,3,273.72,2025-06-16 08:32:00,2025-06-16 09:11:00,39,Alexandria,Wallet,Delivered,Motorbike,31.195082,29.921931,31.191404,29.904982,31.215658,29.910664,1.666106,High,Offline
1,2,U9214,316,65,Sandwich,3,365.82,2025-06-03 21:27:00,2025-06-03 22:00:00,33,Zagazig,Credit Card,Delivered,Motorbike,30.605729,31.503079,30.586047,31.485820,30.580329,31.502380,2.738698,Low,Online
2,3,U7307,357,309,Koshary,3,401.94,2025-06-01 14:48:00,2025-06-01 15:26:00,38,Assiut,Cash,In Transit,Car,27.190180,31.177741,27.164869,31.169218,27.162976,31.189458,2.929079,Medium,Online
3,4,U3612,420,32,Sushi,2,221.18,2025-06-13 02:30:00,2025-06-13 03:22:00,52,Mansoura,Cash,Delivered,Car,31.041846,31.381229,31.035773,31.380440,31.054690,31.401187,0.677498,Low,Online
4,5,U3492,73,364,Koshary,5,355.55,2025-06-06 09:48:00,2025-06-06 10:32:00,44,Mansoura,Wallet,Delivered,Motorbike,31.024141,31.376104,31.026023,31.396881,31.035350,31.389315,1.994769,High,Online

In [4]:
# Cantidad de filas y columnas

df.shape

(100000, 23)

In [6]:
df.head()

,Order_ID,User_ID,Restaurant_ID,Driver_ID,Item_Name,Quantity,Total_Price,Order_Time,Delivery_Time,Delivery_Duration_Minutes,City,Payment_Method,Order_Status,Driver_Vehicle,Restaurant_Lat,Restaurant_Lon,Customer_Lat,Customer_Lon,Driver_Lat,Driver_Lon,Delivery_Distance_km,Traffic_Level,Driver_Availability
0,1,U3522,358,485,Fried Chicken,3,273.72,2025-06-16 08:32:00,2025-06-16 09:11:00,39,Alexandria,Wallet,Delivered,Motorbike,31.195082,29.921931,31.191404,29.904982,31.215658,29.910664,1.666106,High,Offline
1,2,U9214,316,65,Sandwich,3,365.82,2025-06-03 21:27:00,2025-06-03 22:00:00,33,Zagazig,Credit Card,Delivered,Motorbike,30.605729,31.503079,30.586047,31.485820,30.580329,31.502380,2.738698,Low,Online
2,3,U7307,357,309,Koshary,3,401.94,2025-06-01 14:48:00,2025-06-01 15:26:00,38,Assiut,Cash,In Transit,Car,27.190180,31.177741,27.164869,31.169218,27.162976,31.189458,2.929079,Medium,Online
3,4,U3612,420,32,Sushi,2,221.18,2025-06-13 02:30:00,2025-06-13 03:22:00,52,Mansoura,Cash,Delivered,Car,31.041846,31.381229,31.035773,31.380440,31.054690,31.401187,0.677498,Low,Online
4,5,U3492,73,364,Koshary,5,355.55,2025-06-06 09:48:00,2025-06-06 10:32:00,44,Mansoura,Wallet,Delivered,Motorbike,31.024141,31.376104,31.026023,31.396881,31.035350,31.389315,1.994769,High,Online

In [7]:
df.tail()

,Order_ID,User_ID,Restaurant_ID,Driver_ID,Item_Name,Quantity,Total_Price,Order_Time,Delivery_Time,Delivery_Duration_Minutes,City,Payment_Method,Order_Status,Driver_Vehicle,Restaurant_Lat,Restaurant_Lon,Customer_Lat,Customer_Lon,Driver_Lat,Driver_Lon,Delivery_Distance_km,Traffic_Level,Driver_Availability
99995,99996,U7615,524,131,Sushi,2,76.54,2025-06-16 08:04:00,2025-06-16 08:59:00,55,Zagazig,Wallet,Delivered,Car,30.599392,31.506886,30.571412,31.512006,30.594321,31.508916,3.140535,High,Online
99996,99997,U2671,459,450,Shawarma,2,86.50,2025-06-13 12:13:00,2025-06-13 12:43:00,30,Zagazig,Credit Card,Delivered,Car,30.598870,31.507169,30.592725,31.492901,30.607278,31.501169,1.528541,Medium,Online
99997,99998,U2735,12,88,Fried Chicken,4,165.60,2025-06-02 22:51:00,2025-06-02 23:33:00,42,Zagazig,Credit Card,Delivered,Bicycle,30.594678,31.489688,30.592766,31.505024,30.587210,31.510486,1.485960,Low,Online
99998,99999,U7356,570,473,Koshary,4,199.84,2025-06-11 06:09:00,2025-06-11 06:49:00,40,Tanta,Wallet,In Transit,Bicycle,30.786478,31.004323,30.768406,31.013934,30.793099,31.016429,2.204660,Low,Offline
99999,100000,U3960,790,283,Koshary,5,235.30,2025-06-14 23:01:00,2025-06-14 23:48:00,47,Mansoura,Cash,Delivered,Motorbike,31.033496,31.361562,31.046063,31.381597,31.042967,31.387703,2.366264,Low,Online

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Order_ID                   100000 non-null  int64
 1   User_ID                    100000 non-null  object
 2   Restaurant_ID              100000 non-null  int64
 3   Driver_ID                  100000 non-null  int64
 4   Item_Name                  100000 non-null  object
 5   Quantity                   100000 non-null  int64
 6   Total_Price                100000 non-null  float64
 7   Order_Time                 100000 non-null  object
 8   Delivery_Time              100000 non-null  object
 9   Delivery_Duration_Minutes  100000 non-null  int64
 10  City                       100000 non-null  object
 11  Payment_Method             100000 non-null  object
 12  Order_Status               100000 non-null  object
 13  Driver_Vehicle             100000 non-null  object
 14  Restaurant_Lat             100000 non-null  float64
 15  Restaurant_Lon             100000 non-null  float64
 16  Customer_Lat               100000 non-null  float64
 17  Customer_Lon               100000 non-null  float64
 18  Driver_Lat                 100000 non-null  float64
 19  Driver_Lon                 100000 non-null  float64
 20  Delivery_Distance_km       100000 non-null  float64
 21  Traffic_Level              100000 non-null  object
 22  Driver_Availability        100000 non-null  object
dtypes: float64(8), int64(5), object(10)
memory usage: 17.5+ MB

In [9]:
df.columns

Index(['Order_ID', 'User_ID', 'Restaurant_ID', 'Driver_ID', 'Item_Name',
       'Quantity', 'Total_Price', 'Order_Time', 'Delivery_Time',
       'Delivery_Duration_Minutes', 'City', 'Payment_Method', 'Order_Status',
       'Driver_Vehicle', 'Restaurant_Lat', 'Restaurant_Lon', 'Customer_Lat',
       'Customer_Lon', 'Driver_Lat', 'Driver_Lon', 'Delivery_Distance_km',
       'Traffic_Level', 'Driver_Availability'],
      dtype='object')

In [10]:
df.dtypes

Order_ID                       int64
User_ID                       object
Restaurant_ID                  int64
Driver_ID                      int64
Item_Name                     object
Quantity                       int64
Total_Price                  float64
Order_Time                    object
Delivery_Time                 object
Delivery_Duration_Minutes      int64
City                          object
Payment_Method                object
Order_Status                  object
Driver_Vehicle                object
Restaurant_Lat               float64
Restaurant_Lon               float64
Customer_Lat                 float64
Customer_Lon                 float64
Driver_Lat                   float64
Driver_Lon                   float64
Delivery_Distance_km         float64
Traffic_Level                 object
Driver_Availability           object
dtype: object

In [11]:
# Cantidad de valores nulos

df.isnull().sum()

Order_ID                     0
User_ID                      0
Restaurant_ID                0
Driver_ID                    0
Item_Name                    0
Quantity                     0
Total_Price                  0
Order_Time                   0
Delivery_Time                0
Delivery_Duration_Minutes    0
City                         0
Payment_Method               0
Order_Status                 0
Driver_Vehicle               0
Restaurant_Lat               0
Restaurant_Lon               0
Customer_Lat                 0
Customer_Lon                 0
Driver_Lat                   0
Driver_Lon                   0
Delivery_Distance_km         0
Traffic_Level                0
Driver_Availability          0
dtype: int64

In [12]:
# Porcentaje de valores faltantes

(df.isnull().sum()/len(df)*100).sort_values(ascending=False)

Order_ID                     0.0
User_ID                      0.0
Restaurant_ID                0.0
Driver_ID                    0.0
Item_Name                    0.0
Quantity                     0.0
Total_Price                  0.0
Order_Time                   0.0
Delivery_Time                0.0
Delivery_Duration_Minutes    0.0
City                         0.0
Payment_Method               0.0
Order_Status                 0.0
Driver_Vehicle               0.0
Restaurant_Lat               0.0
Restaurant_Lon               0.0
Customer_Lat                 0.0
Customer_Lon                 0.0
Driver_Lat                   0.0
Driver_Lon                   0.0
Delivery_Distance_km         0.0
Traffic_Level                0.0
Driver_Availability          0.0
dtype: float64

In [13]:
# Cantidad de registros duplicados

df.duplicated().sum()

np.int64(0)

# Análisis Exploratorio de Pedidos Delivery mediante Python y SQL

## Módulo:
Friendly SQL & Python para Analytics

## Dataset:
Talabat Enhanced Orders Dataset

## Fuente:
Kaggle

## Objetivo del análisis:
Realizar un análisis exploratorio de datos sobre órdenes de delivery, identificando patrones relacionados con tiempos de entrega, comportamiento de clientes, características de pedidos y variables operativas mediante Python, visualizaciones con Plotly y consultas SQL utilizando DuckDB.

In [14]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

import duckdb

pd.set_option('display.max_columns', None)

In [16]:
df = pd.read_csv("/content/sample_data/talabat_enhanced_orders.csv")

df.head()

,Order_ID,User_ID,Restaurant_ID,Driver_ID,Item_Name,Quantity,Total_Price,Order_Time,Delivery_Time,Delivery_Duration_Minutes,City,Payment_Method,Order_Status,Driver_Vehicle,Restaurant_Lat,Restaurant_Lon,Customer_Lat,Customer_Lon,Driver_Lat,Driver_Lon,Delivery_Distance_km,Traffic_Level,Driver_Availability
0,1,U3522,358,485,Fried Chicken,3,273.72,2025-06-16 08:32:00,2025-06-16 09:11:00,39,Alexandria,Wallet,Delivered,Motorbike,31.195082,29.921931,31.191404,29.904982,31.215658,29.910664,1.666106,High,Offline
1,2,U9214,316,65,Sandwich,3,365.82,2025-06-03 21:27:00,2025-06-03 22:00:00,33,Zagazig,Credit Card,Delivered,Motorbike,30.605729,31.503079,30.586047,31.485820,30.580329,31.502380,2.738698,Low,Online
2,3,U7307,357,309,Koshary,3,401.94,2025-06-01 14:48:00,2025-06-01 15:26:00,38,Assiut,Cash,In Transit,Car,27.190180,31.177741,27.164869,31.169218,27.162976,31.189458,2.929079,Medium,Online
3,4,U3612,420,32,Sushi,2,221.18,2025-06-13 02:30:00,2025-06-13 03:22:00,52,Mansoura,Cash,Delivered,Car,31.041846,31.381229,31.035773,31.380440,31.054690,31.401187,0.677498,Low,Online
4,5,U3492,73,364,Koshary,5,355.55,2025-06-06 09:48:00,2025-06-06 10:32:00,44,Mansoura,Wallet,Delivered,Motorbike,31.024141,31.376104,31.026023,31.396881,31.035350,31.389315,1.994769,High,Online

## Descripción del Dataset

El dataset contiene información histórica de pedidos realizados mediante una plataforma de delivery. Incluye variables relacionadas con clientes, restaurantes, métodos de pago, distancia de entrega, tráfico, duración del pedido y características operativas del servicio.

In [17]:
df.shape

(100000, 23)

In [18]:
print(f"Cantidad de filas: {df.shape[0]}")
print(f"Cantidad de columnas: {df.shape[1]}")

Cantidad de filas: 100000
Cantidad de columnas: 23

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Order_ID                   100000 non-null  int64
 1   User_ID                    100000 non-null  object
 2   Restaurant_ID              100000 non-null  int64
 3   Driver_ID                  100000 non-null  int64
 4   Item_Name                  100000 non-null  object
 5   Quantity                   100000 non-null  int64
 6   Total_Price                100000 non-null  float64
 7   Order_Time                 100000 non-null  object
 8   Delivery_Time              100000 non-null  object
 9   Delivery_Duration_Minutes  100000 non-null  int64
 10  City                       100000 non-null  object
 11  Payment_Method             100000 non-null  object
 12  Order_Status               100000 non-null  object
 13  Driver_Vehicle             100000 non-null  object
 14  Restaurant_Lat             100000 non-null  float64
 15  Restaurant_Lon             100000 non-null  float64
 16  Customer_Lat               100000 non-null  float64
 17  Customer_Lon               100000 non-null  float64
 18  Driver_Lat                 100000 non-null  float64
 19  Driver_Lon                 100000 non-null  float64
 20  Delivery_Distance_km       100000 non-null  float64
 21  Traffic_Level              100000 non-null  object
 22  Driver_Availability        100000 non-null  object
dtypes: float64(8), int64(5), object(10)
memory usage: 17.5+ MB

In [20]:
df.columns

Index(['Order_ID', 'User_ID', 'Restaurant_ID', 'Driver_ID', 'Item_Name',
       'Quantity', 'Total_Price', 'Order_Time', 'Delivery_Time',
       'Delivery_Duration_Minutes', 'City', 'Payment_Method', 'Order_Status',
       'Driver_Vehicle', 'Restaurant_Lat', 'Restaurant_Lon', 'Customer_Lat',
       'Customer_Lon', 'Driver_Lat', 'Driver_Lon', 'Delivery_Distance_km',
       'Traffic_Level', 'Driver_Availability'],
      dtype='object')

In [21]:
df.describe()
df.describe(include="object")

,User_ID,Item_Name,Order_Time,Delivery_Time,City,Payment_Method,Order_Status,Driver_Vehicle,Traffic_Level,Driver_Availability
count,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,9000,9,21367,21396,7,3,3,3,3,2
top,U1071,Shawarma,2025-06-07 07:23:00,2025-06-11 12:05:00,Zagazig,Cash,Delivered,Bicycle,Low,Online
freq,26,11320,16,15,14538,33528,85197,33393,45826,90111

## Distribución de pedidos por ciudad

Este gráfico permite identificar las ciudades con mayor volumen de pedidos registrados dentro del dataset.

In [22]:
# Conteo de pedidos por ciudad

city_orders = df["City"].value_counts().reset_index()

city_orders.columns = ["City", "Total_Orders"]


fig = px.bar(
    city_orders,
    x="City",
    y="Total_Orders",
    title="Cantidad de pedidos por ciudad",
    text="Total_Orders"
)

fig.update_traces(textposition="outside")

fig.show()

### Interpretación

Se observa la distribución de pedidos según ciudad, permitiendo identificar los mercados con mayor demanda dentro de la plataforma de delivery.

In [23]:
payment = df["Payment_Method"].value_counts().reset_index()

payment.columns = ["Payment_Method", "Total"]


fig = px.pie(
    payment,
    names="Payment_Method",
    values="Total",
    title="Distribución de métodos de pago",
    hole=0.4
)

fig.show()

### Interpretación

El gráfico muestra la proporción de utilización de cada método de pago, permitiendo identificar cuáles son los medios preferidos por los usuarios.

In [26]:
fig = px.histogram(
    df,
    x="Delivery_Duration_Minutes",
    nbins=30,
    title="Distribución del tiempo de entrega"
)

fig.show()

### Interpretación

La distribución permite observar el comportamiento habitual de los tiempos de entrega e identificar posibles concentraciones o valores extremos.

In [27]:
fig = px.box(
    df,
    y="Delivery_Duration_Minutes",
    title="Distribución y valores atípicos del tiempo de entrega"
)

fig.show()

### Interpretación

El boxplot permite identificar la dispersión de los tiempos de entrega y detectar posibles valores extremos que podrían representar incidencias operativas.

In [28]:
fig = px.scatter(
    df.sample(5000),
    x="Delivery_Distance_km",
    y="Delivery_Duration_Minutes",
    title="Relación entre distancia y duración de entrega",
    opacity=0.5
)

fig.show()

### Interpretación

Se analiza la relación entre distancia recorrida y duración del pedido. Una tendencia positiva indicaría que los pedidos con mayor distancia requieren más tiempo de entrega.

In [29]:
df.columns.tolist()

['Order_ID',
 'User_ID',
 'Restaurant_ID',
 'Driver_ID',
 'Item_Name',
 'Quantity',
 'Total_Price',
 'Order_Time',
 'Delivery_Time',
 'Delivery_Duration_Minutes',
 'City',
 'Payment_Method',
 'Order_Status',
 'Driver_Vehicle',
 'Restaurant_Lat',
 'Restaurant_Lon',
 'Customer_Lat',
 'Customer_Lon',
 'Driver_Lat',
 'Driver_Lon',
 'Delivery_Distance_km',
 'Traffic_Level',
 'Driver_Availability']

In [30]:
import duckdb

# Registramos el DataFrame como una tabla SQL
duckdb.sql("CREATE TABLE orders AS SELECT * FROM df")

In [31]:
# Mostrar las 10 primeras filas
query1 = duckdb.query("""
SELECT Order_ID, User_ID, City, Total_Price, Delivery_Duration_Minutes
FROM orders
LIMIT 10
""").to_df()

query1

   Order_ID User_ID        City  Total_Price  Delivery_Duration_Minutes
0         1   U3522  Alexandria       273.72                         39
1         2   U9214     Zagazig       365.82                         33
2         3   U7307      Assiut       401.94                         38
3         4   U3612    Mansoura       221.18                         52
4         5   U3492    Mansoura       355.55                         44
5         6   U7439    Mansoura       205.44                         29
6         7   U8948       Cairo       133.94                         40
7         8   U8672    Mansoura       404.80                         41
8         9   U2205    Mansoura       101.03                         47
9        10   U7411       Cairo       130.05                         46

In [35]:
query2 = duckdb.query("""
SELECT Order_ID, City, Delivery_Duration_Minutes, Total_Price
FROM orders
WHERE City = 'Dubai' AND Delivery_Duration_Minutes > 60
LIMIT 20
""").to_df()

query2

Empty DataFrame
Columns: [Order_ID, City, Delivery_Duration_Minutes, Total_Price]
Index: []

In [34]:
query3 = duckdb.query("""
SELECT City, COUNT(*) AS Total_Orders, AVG(Delivery_Duration_Minutes) AS Avg_Duration
FROM orders
GROUP BY City
ORDER BY Total_Orders DESC
""").to_df()

query3

         City  Total_Orders  Avg_Duration
0     Zagazig         14538     37.666185
1       Cairo         14381     37.448369
2       Tanta         14336     37.473284
3      Assiut         14302     37.624878
4        Giza         14232     37.399030
5  Alexandria         14167     37.453872
6    Mansoura         14044     37.572985

In [36]:
query4 = duckdb.query("""
SELECT Order_ID, User_ID, Total_Price, City
FROM orders
ORDER BY Total_Price DESC
LIMIT 10
""").to_df()

query4

   Order_ID User_ID  Total_Price        City
0     46389   U8035       750.00     Zagazig
1     33695   U7286       749.95  Alexandria
2     36994   U1791       749.95      Assiut
3     58635   U9828       749.95    Mansoura
4     83233   U5123       749.95       Tanta
5     83714   U9141       749.95     Zagazig
6      1763   U7201       749.90    Mansoura
7      8487   U4439       749.90       Tanta
8     86935   U3037       749.90       Cairo
9     87086   U6609       749.90    Mansoura

In [37]:
query5 = duckdb.query("""
SELECT City, Payment_Method, AVG(Total_Price) AS Avg_Price, COUNT(*) AS Total_Orders
FROM orders
WHERE Total_Price > 50
GROUP BY City, Payment_Method
ORDER BY Avg_Price DESC
""").to_df()

query5

          City Payment_Method   Avg_Price  Total_Orders
0        Tanta    Credit Card  283.743355          4549
1      Zagazig           Cash  280.599566          4673
2        Tanta         Wallet  280.118907          4667
3   Alexandria    Credit Card  279.261679          4586
4   Alexandria           Cash  279.226220          4637
5       Assiut         Wallet  278.923345          4637
6   Alexandria         Wallet  278.228143          4485
7     Mansoura         Wallet  277.928227          4581
8      Zagazig    Credit Card  277.886235          4683
9         Giza         Wallet  277.203790          4459
10       Cairo    Credit Card  276.974249          4625
11       Cairo         Wallet  276.158109          4589
12      Assiut           Cash  275.951892          4592
13        Giza           Cash  275.941282          4563
14       Tanta           Cash  275.275947          4651
15      Assiut    Credit Card  275.204052          4573
16    Mansoura           Cash  275.076185          4595
17       Cairo           Cash  274.248492          4702
18    Mansoura    Credit Card  272.365245          4404
19        Giza    Credit Card  272.073184          4718
20     Zagazig         Wallet  271.326861          4692